<a href="https://colab.research.google.com/github/Umme-Zaiba/HDI-/blob/main/HDI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

HUMAN DEVELOPEMNT INDEX -DATASET

1.Take a dataset and scale

In [ ]:
import pandas as pd 
df = pd.read_csv('https://raw.githubusercontent.com/Umme-Zaiba/HDI-/main/HDI_dataset_new.csv')
df

HDI rank                   Country  Human Development Index (HDI)  \
0           1               Switzerland                          0.962   
1           2                    Norway                          0.961   
2           3                   Iceland                          0.959   
3           4    Hong Kong, China (SAR)                          0.952   
4           5                 Australia                          0.951   
..        ...                       ...                            ...   
186       187                   Burundi                          0.426   
187       188  Central African Republic                          0.404   
188       189                     Niger                          0.400   
189       190                      Chad                          0.394   
190       191               South Sudan                          0.385   

     Life expectancy at birth  Expected years of schooling  \
0                        84.0                         16.5   
1                        83.2                         18.2   
2                        82.7                         19.2   
3                        85.5                         17.3   
4                        84.5                         21.1   
..                        ...                          ...   
186                      61.7                         10.7   
187                      53.9                          8.0   
188                      61.6                          7.0   
189                      52.5                          8.0   
190                      55.0                          5.5   

     Mean years of schooling  Gross national income (GNI) per capita  \
0                       13.9                                 66933.0   
1                       13.0                                 64660.0   
2                       13.8                                 55782.0   
3                       12.2                                 62607.0   
4                       12.7                                 49238.0   
..                       ...                                     ...   
186                      3.1                                   732.0   
187                      4.3                                   966.0   
188                      2.1                                  1240.0   
189                      2.6                                  1364.0   
190                      5.7                                   768.0   

     GNI per capita rank minus HDI rank  HDI rank.1  
0                                     5           3  
1                                     6           1  
2                                    11           2  
3                                     6           4  
4                                    18           5  
..                                  ...         ...  
186                                   4         187  
187                                   1         188  
188                                  -3         189  
189                                  -7         190  
190                                  -1         191  

[191 rows x 9 columns]

In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
df.size

1719

In [ ]:
df.shape

(191, 9)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 191 entries, 0 to 190
Data columns (total 9 columns):
 #   Column                                  Non-Null Count  Dtype  
---  ------                                  --------------  -----  
 0   HDI rank                                191 non-null    int64  
 1   Country                                 191 non-null    object 
 2   Human Development Index (HDI)           191 non-null    float64
 3   Life expectancy at birth                191 non-null    float64
 4   Expected years of schooling             191 non-null    float64
 5   Mean years of schooling                 191 non-null    float64
 6   Gross national income (GNI) per capita  191 non-null    float64
 7   GNI per capita rank minus HDI rank      191 non-null    int64  
 8   HDI rank.1                              191 non-null    int64  
dtypes: float64(5), int64(3), object(1)
memory usage: 13.6+ KB


In [ ]:
#Inputs - Life expectancy at birth, Mean years of schooling, Gross national income (GNI) per capita.
x = df.iloc[:,3:7]
x

Life expectancy at birth  Expected years of schooling  \
0                        84.0                         16.5   
1                        83.2                         18.2   
2                        82.7                         19.2   
3                        85.5                         17.3   
4                        84.5                         21.1   
..                        ...                          ...   
186                      61.7                         10.7   
187                      53.9                          8.0   
188                      61.6                          7.0   
189                      52.5                          8.0   
190                      55.0                          5.5   

     Mean years of schooling  Gross national income (GNI) per capita  
0                       13.9                                 66933.0  
1                       13.0                                 64660.0  
2                       13.8                                 55782.0  
3                       12.2                                 62607.0  
4                       12.7                                 49238.0  
..                       ...                                     ...  
186                      3.1                                   732.0  
187                      4.3                                   966.0  
188                      2.1                                  1240.0  
189                      2.6                                  1364.0  
190                      5.7                                   768.0  

[191 rows x 4 columns]

In [ ]:
x = df.iloc[:,3:7].values
x

In [ ]:
y = df.iloc[:,2]  #output- Human Development Index
y

0      0.962
1      0.961
2      0.959
3      0.952
4      0.951
       ...  
186    0.426
187    0.404
188    0.400
189    0.394
190    0.385
Name: Human Development Index (HDI), Length: 191, dtype: float64

In [ ]:
y = df.iloc[:,2].values
y

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y)

In [ ]:
print(x.shape)
print(x_train.shape)
print(x_test.shape)

(191, 4)
(143, 4)
(48, 4)


In [ ]:
print(y.shape)
print(y_train.shape)
print(y_test.shape)

(191,)
(143,)
(48,)


In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.fit_transform(x_test)

In [ ]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [ ]:
model.fit(x_train,y_train)

LinearRegression()

In [ ]:
y_pred = model.predict(x_test)
y_pred 


array([1.01851973, 0.82932166, 1.00203767, 0.8446063 , 0.7195865 ,
       0.88019057, 0.78148203, 0.86098422, 0.72626635, 0.36352429,
       0.48392127, 0.65420387, 0.69133992, 0.76038655, 0.47919352,
       0.67434851, 0.54554712, 0.55775347, 0.7487499 , 0.98696006,
       0.78225355, 0.88061756, 0.90867491, 0.63277821, 0.49181913,
       0.55095338, 0.75225217, 0.79345951, 0.773212  , 0.46454149,
       0.80749345, 1.00036901, 0.68114725, 0.42989849, 0.53740899,
       0.54743342, 0.79914773, 0.69932547, 0.87345454, 0.83786279,
       0.94768439, 0.74678048, 0.76919391, 0.47623156, 0.89451029,
       0.65153476, 0.74707786, 0.73522864])

In [ ]:
type(y_pred)

numpy.ndarray

In [ ]:
import numpy as np
#y_pred= np.round(y_pred)
y_pred

array([1.01851973, 0.82932166, 1.00203767, 0.8446063 , 0.7195865 ,
       0.88019057, 0.78148203, 0.86098422, 0.72626635, 0.36352429,
       0.48392127, 0.65420387, 0.69133992, 0.76038655, 0.47919352,
       0.67434851, 0.54554712, 0.55775347, 0.7487499 , 0.98696006,
       0.78225355, 0.88061756, 0.90867491, 0.63277821, 0.49181913,
       0.55095338, 0.75225217, 0.79345951, 0.773212  , 0.46454149,
       0.80749345, 1.00036901, 0.68114725, 0.42989849, 0.53740899,
       0.54743342, 0.79914773, 0.69932547, 0.87345454, 0.83786279,
       0.94768439, 0.74678048, 0.76919391, 0.47623156, 0.89451029,
       0.65153476, 0.74707786, 0.73522864])

In [ ]:
y_test

array([0.947, 0.822, 0.952, 0.846, 0.747, 0.863, 0.767, 0.858, 0.731,
       0.394, 0.5  , 0.686, 0.717, 0.785, 0.511, 0.706, 0.512, 0.597,
       0.767, 0.942, 0.782, 0.855, 0.896, 0.639, 0.492, 0.586, 0.77 ,
       0.802, 0.774, 0.508, 0.809, 0.941, 0.706, 0.465, 0.534, 0.558,
       0.8  , 0.709, 0.866, 0.832, 0.925, 0.768, 0.78 , 0.426, 0.875,
       0.662, 0.759, 0.752])

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_pred,y_test)*100 

ValueError: ignored